version: "3.5"

networks:
    whale:
        external:
            name: "whale_bridge"

services:
    server:
        container_name: drone_server
        image: drone/drone:1
        restart: always
        environment:
            - DRONE_GITEA_SERVER=http://gitea.whalem.net
            - DRONE_GITEA_CLIENT_ID=
            - DRONE_GITEA_CLIENT_SECRET=
            - DRONE_RPC_SECRET=
            - DRONE_SERVER_HOST=drone.whalem.net
            - DRONE_SERVER_PROTO=http
            - DRONE_USER_CREATE=
        networks:
            whale:
                ipv4_address: 10.0.0.130
        dns:
            - 10.0.0.100
        volumes:
            - ./data:/data
    runner:
        container_name: drone_runner
        image: drone/drone-runner-docker:1
        restart: always
        depends_on:
            - server
        dns:
            - 10.0.0.100
        networks:
            - whale
        environment:
            - DRONE_RPC_PROTO=http
            - DRONE_RPC_HOST=drone.whalem.net
            - DRONE_RPC_SECRET=
            - DRONE_RUNNER_CAPACITY=2
            - DRONE_RUNNER_NAME=whale
            - DRONE_RUNNER_NETWORKS=whale_bridge
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
