version: "3.5"

networks:
    whale:
        external:
            name: "whale_bridge"

services:
    server:
        container_name: gitea
        image: gitea/gitea:1.13.1
        restart: always
        environment:
            - USER_UID=1001
            - USER_GID=1001
            - DISABLE_SSH=true
        networks:
            whale:
                ipv4_address: 10.0.0.120
        dns:
            - 10.0.0.100
        volumes:
            - ./gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
