version: "3.5"

networks:
    whale:
        external:
            name: "whale_bridge"

services:
    server:
        container_name: "whale_dns"
        image: unbound
        restart: always
        networks:
            whale:
                ipv4_address: 10.0.0.100
        volumes:
            - type: bind
              source: /home/mk/whalemountain/unbound/records/a-records.conf
              target: /opt/unbound/etc/unbound/a-records.conf
              read_only: true
