version: "3.5"

networks:
    whale:
        external:
            name: "whale_bridge"

services:
    server:
        container_name: filegea
        build: ./Dockerfile
        image: filegea
        restart: always
        networks:
            whale:
                ipv4_address: 10.0.0.140
        dns:
            - 10.0.0.100
        volumes:
            - ./Data:/opt/filegea/Data
